### ISSUE TITLE
About mIOU score

### ISSUE THREAD

**Issue by liamlin5566** [cardwing/Codes-for-PVKD#17]
Hi, thank you for sharing this work.
I want to know why the mIOU of Cylinder3D  is 71.8, which is higher than original work in leaderboard. Do yo do any modification in training process?

**Comment by cardwing** [comment]
We iteratively finetune the model with small learning rates. Instance augmentation is also adopted (Panoptic-PolarNet, CVPR 2021). You can have a try.

**Comment by cardwing** [comment]
The pretrained weights can be reproduced by us on the A100 server. I have responded to most of the issues. I admit that the codes are very similar to the Cylinder3D codes since the distillation codes are not provided. The issues are created by other researchers and I just wonder what's your purpose on slandering us. @lfl256 I have gone through your github account and find that your activity is private. I wonder why you do this.

**Comment by cardwing** [comment]
It is strange that why you are so hostile to us. The codebase is still under construction and more modules will be added. @lfl256

**Comment by cardwing** [comment]
First, "There is no training code" is obviously a fake comment. I provide the normal training code. The distillation codes are under preparation.
Second, "You paid many bot accounts to get stars for this repo". We only recommend this repo to our friends and colleagues. How do you get the conclusion that I paid them? @lfl256

**Comment by liamlin5566** [comment]
@cardwing thanks for your response. And, @lfl256, my account is individual,  not belonging to the author. The method I test is Cylinder3d (single scan) and use LMNet to distinguish moving object,  so the score is similar to original Cylinder3d. Sorry for confusing you.

**Comment by liamlin5566** [comment]
-.。。 一！

FS ***@***.***> 於 2022年8月19日 週五 12:08 寫道：
