### ISSUE TITLE
Why Waymo disqualified your result from the 2022 Waymo Open Dataset Challenge?

### ISSUE THREAD

**Issue by IrohXu** [cardwing/Codes-for-PVKD#7]
![image](https://user-images.githubusercontent.com/40520605/175591797-ec9c74cc-004e-4aec-98be-e3bf5f91df1c.png)

**Comment by cardwing** [comment]
Our Shanghai AI Lab is considered as a company by the Waymo organizers and they only allow a company to participate in one track (they considered submissions in camera-only 3D detection as legal since it was submitted the earliest). Other teams are disqualified for a similar reason in the 3D seg challenge. Our results are admitted by Waymo and we will release these powerful models as well as training details soon.
